indent = 4
margin = 80
always_for_in = true
whitespace_typedefs = true
whitespace_ops_in_indices = true
remove_extra_newlines = false

function numerical_gradient(
    f::Function,
    x::VecOrMat{Float64},
)::VecOrMat{Float64}
    grad = zeros(size(x))
    grad = ForwardDiff.gradient(f, x)
    return grad
end